version: 0.2
phases:
  install:
    commands: 
      - echo "[Install phase]"
      - pip install -r requirements.txt -t .
      - ls
  pre_build:
    commands: 
    # null
  build:
    commands:
      - echo "Starting SAM packaging `date` in `pwd`"
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yaml
  post_build:
    commands:
      - echo "SAM packaging completed on `date`"
artifacts:
  files:
    - packaged.yaml
  discard-paths: 'yes'
cache:
  paths: 
  # null