AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FraudPy Dashboard API

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: python3.11
    Environment:
      Variables:
        FRAUD_LISTS_TABLE:
          Fn::ImportValue: fraud-service-FraudPyV1ListsTable
        FRAUD_LIMITS_TABLE:
          Fn::ImportValue: fraud-service-FraudPyV1LimitsTable
        FRAUD_PROCESSED_TRANSACTIONS_TABLE:
          Fn::ImportValue: fraud-service-FraudPyV1ProcessedTransactionsTable
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  LimitsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./limits
      Handler: lambda_handler.lambda_handler
      Events:
        LimitsAccount:
          Type: Api
          Properties:
            Path: /limits/account
            Method: ANY
        LimitsAccountApplication:
          Type: Api
          Properties:
            Path: /limits/account-processor
            Method: ANY
        LimitsAccountApplicationMerchant:
          Type: Api
          Properties:
            Path: /limits/account-processor-merchant
            Method: ANY
        LimitsAccountApplicationMerchantProduct:
          Type: Api
          Properties:
            Path: /limits/account-processor-merchant-product
            Method: ANY
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - Statement:
          - Effect: Allow
            Action:
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:DescribeTable
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:Scan
            Resource: '*'
    
  ListsCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lists
      Handler: create.lambda_handler
      Events:
        CreateList:
          Type: Api
          Properties:
            Path: /lists
            Method: POST
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - Statement:
          - Effect: Allow
            Action:
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:DescribeTable
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:Scan
            Resource: '*'
  
  CreateNewListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lists
      Handler: create_new_list.lambda_handler
      Events:
        CreateNewList:
          Type: Api
          Properties:
            Path: /lists/new
            Method: POST
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - Statement:
          - Effect: Allow
            Action:
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:DescribeTable
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:Scan
            Resource: '*'

  ListsReadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lists
      Handler: read.lambda_handler
      Events:
        ReadList:
          Type: Api
          Properties:
            Path: /lists
            Method: GET
        ReadListByListType:
          Type: Api
          Properties:
            Path: /lists/by-list-type
            Method: GET
        ReadListByChannel:
          Type: Api
          Properties:
            Path: /lists/by-channel
            Method: GET
        ReadListByEntityType:
          Type: Api
          Properties:
            Path: /lists/by-entity-type
            Method: GET
        ReadListByDateRange:
          Type: Api
          Properties:
            Path: /lists/by-date-range
            Method: GET
        ReadListByEntityTypeAndListType:
          Type: Api
          Properties:
            Path: /lists/by-list-type-and-entity-type
            Method: GET
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - Statement:
          - Effect: Allow
            Action:
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:DescribeTable
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:Scan
            Resource: '*'
  
  GetAllListsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lists
      Handler: get_all_list_types.lambda_handler
      Events:
        GetAllLists:
          Type: Api
          Properties:
            Path: /lists/new/all
            Method: GET
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - Statement:
          - Effect: Allow
            Action:
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:DescribeTable
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:Scan
            Resource: '*'

  ListsUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lists
      Handler: update_2.lambda_handler
      Events:
        UpdateList:
          Type: Api
          Properties:
            Path: /lists
            Method: PUT
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - Statement:
          - Effect: Allow
            Action:
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:DescribeTable
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:Scan
            Resource: '*'
  
  UpdateListTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lists
      Handler: update_list_type.lambda_handler
      Events:
        UpdateListType:
          Type: Api
          Properties:
            Path: /lists/new/update
            Method: PUT
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - Statement:
          - Effect: Allow
            Action:
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:DescribeTable
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:Scan
            Resource: '*'

  ListsDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lists
      Handler: delete.lambda_handler
      Events:
        DeleteList:
          Type: Api
          Properties:
            Path: /lists
            Method: DELETE
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - Statement:
          - Effect: Allow
            Action:
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:DescribeTable
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:Scan
            Resource: '*'
  
  DeleteListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lists
      Handler: delete_list_type.lambda_handler
      Events:
        DeleteListType:
          Type: Api
          Properties:
            Path: /lists/new/delete
            Method: DELETE
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - Statement:
          - Effect: Allow
            Action:
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:DescribeTable
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:Scan
            Resource: '*'
  
  EvaluatedTransactionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./evaluated_transactions
      Handler: app_with_pagination_3.lambda_handler
      Events:
        QueryEvaluatedTransactions:
          Type: Api
          Properties:
            Path: /evaluated-transactions
            Method: GET
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - DynamoDBCrudPolicy:
            TableName: '*'
  
  MerchantsInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./merchants_info
      Handler: app.lambda_handler
      Events:
        CreateOrUpdateMerchant:
          Type: Api
          Properties:
            Path: /merchants
            Method: POST
        GetMerchant:
          Type: Api
          Properties:
            Path: /merchants
            Method: GET
        DeleteMerchants:
          Type: Api
          Properties:
            Path: /merchants
            Method: DELETE
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - DynamoDBCrudPolicy:
            TableName: '*'
  
  MerchantProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./merchant_products
      Handler: app.lambda_handler
      Events:
        CreateOrUpdateMerchantProduct:
          Type: Api
          Properties:
            Path: /merchant-products
            Method: POST
        GetMerchantProduct:
          Type: Api
          Properties:
            Path: /merchant-products
            Method: GET
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - DynamoDBCrudPolicy:
            TableName: '*'

  TransactionSummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./transactions_summary
      Handler: app.lambda_handler
      Events:
        QueryTransactionSummary:
          Type: Api
          Properties:
            Path: /transaction-summary
            Method: GET
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - DynamoDBCrudPolicy:
            TableName: '*'
  
  CaseManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./case_management
      Handler: app_2.lambda_handler
      Events:
        CreateCase:
          Type: Api
          Properties:
            Path: /case
            Method: POST
        UpdateCaseStatus:
          Type: Api
          Properties:
            Path: /case/status
            Method: PUT
        GetCase:
          Type: Api
          Properties:
            Path: /case
            Method: GET
        GetAllCases:
          Type: Api
          Properties:
            Path: /cases/open
            Method: GET
        GetAllClosedCases:
          Type: Api
          Properties:
            Path: /cases/closed
            Method: GET
        CloseCase:
          Type: Api
          Properties:
            Path: /case/close
            Method: PUT
        CreateReport:
          Type: Api
          Properties:
            Path: /report
            Method: POST
        GetAllCaseReports:
          Type: Api
          Properties:
            Path: /reports
            Method: GET
        EditReport:
          Type: Api
          Properties:
            Path: /report
            Method: PUT
        DeleteReport:
          Type: Api
          Properties:
            Path: /report
            Method: DELETE
        CreateInvestigator:
          Type: Api
          Properties:
            Path: /investigator
            Method: POST
        GetInvestigator:
          Type: Api
          Properties:
            Path: /investigator
            Method: GET
        GetAllInvestigators:
          Type: Api
          Properties:
            Path: /investigators
            Method: GET
        UpdateInvestigator:
          Type: Api
          Properties:
            Path: /investigator
            Method: PUT
        DeleteInvestigator:
          Type: Api
          Properties:
            Path: /investigator
            Method: DELETE
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - DynamoDBCrudPolicy:
            TableName: '*'

  
  UNListManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lists
      Handler: un_list.lambda_handler
      Events:
        UpdateList:
          Type: Api
          Properties:
            Path: /unlist/refresh
            Method: POST
        GetList:
          Type: Api
          Properties:
            Path: /unlist/get
            Method: GET
      Policies:
        - AWSXrayWriteOnlyAccess
        - AWSLambdaSQSQueueExecutionRole
        - DynamoDBCrudPolicy:
            TableName: '*'

# Make sure to add the necessary IAM permissions for this function to access your DynamoDB table

Outputs:
  ApiURL:
    Description: "API Gateway endpoint URL for Prod stage"
    Value:
      Fn::Sub: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
